### ISSUE TITLE
adding jupyter con 2020 example to the example collection

### ISSUE THREAD

**Issue by joseberlines** [cytoscape/ipycytoscape#175]
I find that the examples you explained in the jupy 2020 are very acclaratory and contain all the data that a edge or node can contain. this is very useful for being able to understand the fully power of ipycytoscape.
adding that jupyter file to the collection of examples would be wonderfull.

From the same jupyter notebook example I would include in read the docs a section including all the attributes of nodes and edges. it suffices to copy and paste the list appearing in the video on min 15.06 into a section of read the docs. The atributes are basically self explanatory

**Comment by marimeireles** [comment]
Hey @joseberlines, thanks for the kind words :)
I just looked for the notebook here and I don't have it! Fortunately I've uploaded it to the conference dropbox, I sent an email and I'm waiting for someone to get back to me with the file so I can upload it here.
Cheers!

**Comment by marimeireles** [comment]
Hey @joseberlines we can reopen this.
I'm gonna ping the responsible folks one more time!

**Comment by marimeireles** [comment]
@SylvainCorlay were you able to have a look at this?
You have someone else I can ping about it?

**Comment by marimeireles** [comment]
This was lost, unfortunately.
I wrote a new notebook for scypy and will make it available here.
