### ISSUE TITLE
updating graph style by adding element to the set_style list not working.

### ISSUE THREAD

**Issue by joseberlines** [cytoscape/ipycytoscape#197]
I have a graph called ipycytoscape_obj9 with a particular my_style.

assume I add a node and two edges to that node.
And then I want to update also the style of the edges.
as in:
```
my_style.append({'selector': 'edge[id = "line6"]',
                 'style': {
                     'font-family': 'arial',
                     'font-size': '10px',
                     'label': 'data(label)'}})
my_style.append({'selector': 'edge[id = "line7"]',
                 'style': {
                     'font-family': 'arial',
                     'font-size': '10px',
                     'label': 'data(label)'}})
ipycytoscape_obj9.set_style(my_style)
```

If I print out in the next cell the graph I would expect that the new appended styles are taking into account for edges 6 and 7. that is not the case.

Only starting from scratch with a new graph the new styles would be matched by printing/displaying/rendering the graph:
```
ipycytoscape_obj10 = ipycytoscape.CytoscapeWidget()
ipycytoscape_obj10.graph.add_graph_from_json(railnetJSON)
ipycytoscape_obj10.graph.add_node(station_NUR)
ipycytoscape_obj10.graph.add_edges([new_edge1,new_edge2])
ipycytoscape_obj10.set_style(my_style)
ipycytoscape_obj10
```

looking at the source code there is no method to "add_style" so I assumed that changing the json style and pass it again to the graph will do it. but it does not.

POST EDIT: I have the impression that the graph including styles has to be re-created from scratch. adding nodes and edges is ok, but adding styles isnt.

**Comment by ianhi** [comment]
What version of ipycytoscape are you seeing this on?

**Comment by joseberlines** [comment]
print(ipycytoscape.__version__)
1.0.4

**Comment by marimeireles** [comment]
Thanks for the issue @joseberlines will investigate now =)

**Comment by marimeireles** [comment]
This happens because of #56. I'm closing this and moving the discussion to there.
Thanks for the issue!
