### ISSUE TITLE
Moving ipycytoscape to the Cytoscape GitHub organization

### ISSUE THREAD

**Issue by SylvainCorlay** [cytoscape/ipycytoscape#262]
After discussions with the leadership of the Cytoscape organization, and with the plasmabio project, we are now planning on moving the ipycytoscape project outside of the QuantStack organization to the Cytoscape organization.

We hope that this will reflect more the multi-stakeholder nature of the project and help attract new contributors.

This will probably happen in the course of next week. Afer we move the project, there may be a short period where we need to set things up so that it works in the new organization (commit rights, CI, URLs).

**Comment by marimeireles** [comment]
Thanks Sylvain and everyone involved! :)
