### ISSUE TITLE
Add git tag for 1.2.2

### ISSUE THREAD

**Issue by shadiakiki1986** [cytoscape/ipycytoscape#282]
Git commit 6b228e34d669f18c8e70ee7eff8f8d4f34490e51 is for version 1.2.2 as published on pypi, but it's not tagged in the git repository.

**Comment by ianhi** [comment]
Thanks for the catch! It looks like that was released manually rather than via github actions. Should be fixed now and available here: https://github.com/cytoscape/ipycytoscape/tree/1.2.2
