### ISSUE TITLE
Enable pre-commit (and pre-commit.ci)

### ISSUE THREAD

**Issue by ianhi** [cytoscape/ipycytoscape#286]
I really like using pre-commit.ci and we've started using it on ipympl which has been nice (example auto commit: https://github.com/matplotlib/ipympl/pull/396/commits/b9e2c88b882743b51e26c26051be8e976e8e7f91). I would like to enable it here as well but don't seem to have the permissions. So heads up to @maxkfranz  (I think?) that I requested it on the website so a notification may have popped up for you somewhere.

**Comment by maxkfranz** [comment]
It looks like this should be enabled

**Comment by ianhi** [comment]
thanks! config added in https://github.com/cytoscape/ipycytoscape/pull/300
