### ISSUE TITLE
Publish `1.3.0` and `1.3.1` on npm

### ISSUE THREAD

**Issue by ianhi** [cytoscape/ipycytoscape#289]
### Problem
Due to issues with secrets the automated release script didn't work - see #288 for details.

So I manually published `1.3.0` to pypi, however I don't have permissions to push the npm package so I was unable to publish that.

### Proposed Solution
Can I have push access to the npm repo? and/or can someone with access push 1.3.0

**Comment by marimeireles** [comment]
Sure thing! :)

https://www.npmjs.com/package/jupyter-cytoscape/access

I think you must have the same access that everyone else now?
I'll wait for you to confirm that to close this issue.

**Comment by marimeireles** [comment]
Did you get access to this @ianhi ?

**Comment by ianhi** [comment]
I don't think so :( 

![image](https://user-images.githubusercontent.com/10111092/150007098-9f0786e2-2577-4f8b-8a93-e6632cbeeadb.png)


I missed this yesterday, maybe something expired?

**Comment by marimeireles** [comment]
Humm, so this: https://www.npmjs.com/~ianhi
is not you?

**Comment by ianhi** [comment]
ooh indeed not. npm is one of the places on the internet where ianhi was already taken :( i'm https://www.npmjs.com/~ianhuntisaak on npm

**Comment by marimeireles** [comment]
A random Ian had complete access to our npm repo :o!

Added, now we should be good :)
