### ISSUE TITLE
Conda does not have the latest version

### ISSUE THREAD

**Issue by afonit** [cytoscape/ipycytoscape#293]
In the readme for installation I see it says:
```bash
mamba install -c conda-forge ipycytoscape
```

When I installed it I saw it was version `1.2.2` but on github I see `1.3.0` has been released.

Searching conda I found the package page:
https://anaconda.org/conda-forge/ipycytoscape

It looks like that is pointing to: https://github.com/QuantStack/ipycytoscape/

I see in the history there was a transfer of ownership to the cytoscape org.

I thought I would just point this discrepancy out since the readme shows conda-forge as a source for installation.

**Comment by ianhi** [comment]
The link is actually ok because it redirects (or maybe because it pulls from pypi?) but the build failed due to some dependency issues. going to release one soon that should fix

**Comment by ianhi** [comment]
sadly that did not fix it. there are other build issues :'( https://github.com/conda-forge/ipycytoscape-feedstock/pull/21

**Comment by marimeireles** [comment]
Super weird error.
Works on node 14, fails on 16, 17. I can kinda reproduce it locally but not sure what's causing it!
I asked a question in the conda-forge channel, in the meanwhile I'll try to fix it by sending another version bump... Let's see.
I'm thinking about just skipping v. 1.3.1 and 1.3.0 on conda-forge.

**Comment by ianhi** [comment]
for future me to not click through the error logs. The relevant error is:

```
  npm ERR! While resolving: jupyter-cytoscape@1.3.1
  npm ERR! Found: karma@3.1.4
  npm ERR! node_modules/karma
  npm ERR!   dev karma@"^3.0.0" from the root project
  npm ERR!
  npm ERR! Could not resolve dependency:
  npm ERR! peer karma@"1 || 2" from karma-typescript@3.0.13
  npm ERR! node_modules/karma-typescript
  npm ERR!   dev karma-typescript@"^3.0.13" from the root project
  npm ERR!

```

**Comment by ianhi** [comment]
notably our karma-typescript (3.0.13) is pretty out of date - currently on 5.5.2

I wonder if updating that would solve the issue.

**Comment by marimeireles** [comment]
Yeah, the weird thing is that I tried locally and it worked for me.
But if I make X changes (idk which changes are) then, it doesn't work anymore.
I bumped the klarna versions and it's still working locally, just made a patch on conda-forge.

**Comment by marimeireles** [comment]
So that appraised the gods of the CI. I'm leaving it like that, because it was working on my computer regardless!
I just made a patch. I'll add a PR to change the `package.json` here too.
Thanks @ianhi 🌸
