### ISSUE TITLE
Date is not JSON serializable

### ISSUE THREAD

**Issue by pwrose** [cytoscape/ipycytoscape#298]
### Bug report

**Bug summary**

If a node_attribute, e.g. a Date object, is not JSON serializable, I get the following error:
```
      1 widget1 = ipycytoscape.CytoscapeWidget()
----> 2 widget1.graph.add_graph_from_neo4j(subgraph1)

~/miniconda3/envs/dkg/lib/python3.7/site-packages/ipycytoscape/cytoscape.py in add_graph_from_neo4j(self, g)
    739             # create node
    740             node_instance = Node()
--> 741             _set_attributes(node_instance, node_attributes)
    742             node_list.append(node_instance)
    743 

~/miniconda3/envs/dkg/lib/python3.7/site-packages/ipycytoscape/cytoscape.py in _set_attributes(instance, data)
    250             setattr(instance, k, v)
    251         else:
--> 252             instance.data[k] = v

...

~/miniconda3/envs/dkg/lib/python3.7/site-packages/jupyter_client/jsonutil.py in json_default(obj)
    124         return float(obj)
    125 
--> 126     raise TypeError("%r is not JSON serializable" % obj)
    127 
    128 

TypeError: Date(2020, 11, 6) is not JSON serializable
```

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

**Expected outcome**

**Version Info**

  * ipycytoscape version (`import ipycytoscape; print(ipycytoscape.__version__)`) : 
  * Python version:
  * Jupyter(Lab) version:

**Comment by marimeireles** [comment]
I'm thinking if all data shouldn't be serialized?
What if you try to convert it with [dumps](https://docs.python.org/3/library/json.html)?
Idk if this make sense, sorry if it doesn't, but I'm struggling to find a good generic solution for this.

You think we should convert it always before calling this method `add_graph_from_neo4j`, for example? Or do you have any input on what should we do here?

Thanks for opening the issue! Never thought about this before.

**Comment by marimeireles** [comment]
Ah, this issue was fixed by your PR, correct?
Sorry for the confusion :)

**Comment by pwrose** [comment]
Yes, the pr fixes the issue in a general way.
