### ISSUE TITLE
What to do with the pre-commit tool

### ISSUE THREAD

**Issue by marimeireles** [cytoscape/ipycytoscape#299]
We're getting this kind of error of our pre-commit thingy: https://results.pre-commit.ci/run/github/238460517/1642317160.jW4EH-NuS1eqYcHn0ZI9iA

I don't really understand where it's coming from. The only pre-commit thing we have is:

```
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
```

on our package.json. @ianhi any idea? Seems like we need a `.pre-commit-config.yaml` file to fix it, does this make sense?
Should we migrate to another tool?

**Comment by ianhi** [comment]
indeed we do need that file - sorry i never added it after the tool was enabled. This is nice because it can combine fixes for python and ts into one tool. I'd suggest we follow the one ipympl uses - I can make a pr
