### ISSUE TITLE
Error: Module jupyter-cytoscape, semver range ^1.3.2 is not registered as a widget module

### ISSUE THREAD

**Issue by gt-eq-1998** [cytoscape/ipycytoscape#320]
Still persist when installing with `pip install ipycytoscape`
`Error: Module jupyter-cytoscape, semver range ^1.3.2 is not registered as a widget module`

Version Info

- ipycytoscape version (import ipycytoscape; print(ipycytoscape.__version__)) : 1.3.2

- Python version: 3.8.12

- Jupyter(Lab) version: 3.2.4

_Originally posted by @gt-eq-1998 in https://github.com/cytoscape/ipycytoscape/issues/294#issuecomment-1068011856_

**Comment by marimeireles** [comment]
Hey @gt-eq-1998, I can't reproduce this issue.
I wonder if you're having some conflicts with your environment.
Where is your python coming from? 
`which python`
Also, do you have restrictions regarding using the conda/mamba ecosystem?
If you tell me more about your env. I can try to reproduce it better, e.g what are you using the manage your env?

**Comment by gt-eq-1998** [comment]
> Hey @gt-eq-1998, I can't reproduce this issue. I wonder if you're having some conflicts with your environment. Where is your python coming from? `which python` Also, do you have restrictions regarding using the conda/mamba ecosystem? If you tell me more about your env. I can try to reproduce it better, e.g what are you using the manage your env?

Hey @marimeireles , I'm using conda environment with poetry, I'm not sure about conflict stuff , but all thing in my env working.
What do you mean by restrictions?

**Comment by marimeireles** [comment]
Okay.
Is not recommended to mix two different package managers, like pip and conda, for example.
The problem is that their solvers interact and this kind of issue occurs.
My advice is that you stick with one package manager and try again, this should fix your issue.
